<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\Flyworm.App\Assets\app.ico</ApplicationIcon>
    <RootNamespace>Flyworm.Setup</RootNamespace>
    <AssemblyName>Flyworm-Setup</AssemblyName>
    <Version>1.0.1</Version>
    <Product>Flyworm</Product>
    <Description>Flyworm kurulum</Description>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="..\Flyworm.App\Assets\logo.png" Link="Assets\logo.png" />
    <Resource Include="..\Flyworm.App\Assets\app.ico" Link="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Payload.zip" Condition="Exists('Payload.zip')" />
  </ItemGroup>
</Project>
